# Site settings
title: Iowa Ruby Brigade
url: "http://www.iowaruby.org"
collections:
  meetings:
    output: true
  jobs:
    output: true

# Build settings
markdown: kramdown

twitter_username: iowaruby

exclude: [Gemfile, Gemfile.lock]
